### ISSUE TITLE
Home - Contents are in English rather than being in French

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/hairdom#14]
1) Open the website 'https://hairdom.herokuapp.com/'.
2) Scroll to the middle of the page and look at the contents.

Note: The contents are in English rather than being in French.

![hd - texts in english](https://cloud.githubusercontent.com/assets/2522583/5716512/12877734-9b16-11e4-8643-9ca6e61d126c.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
Verified in 'https://hairdom.herokuapp.com/', issue is fixed. Closing the issue.
