### ISSUE TITLE
Cart - Replace the text in the button next to Promocode field with 'Appliquer'

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/hairdom#16]
1) Open the website 'https://hairdom.herokuapp.com/'.
2) Select any product and go to Cart page.
3) Look at the text in the button next ot the 'Code Promo' field.

Note: The text on the button is currently 'Mise à jour', instead replace it with 'Appliquer'.

![hd - replace button text in cart](https://cloud.githubusercontent.com/assets/2522583/5716658/c700b6c4-9b18-11e4-8d27-8832c422f0c7.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
Verified in 'https://hairdom.herokuapp.com/', issue is fixed. Closing the issue.
