### ISSUE TITLE
Suggestion - Cart - Introduce a confirmation pop-up when user tries to clear the cart

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/hairdom#17]
1) Open the website 'https://hairdom.herokuapp.com/'.
2) Select any product and go to Cart page.
3) Click on the 'Vider le panier' button.

Note: The site should show a confirmation pop-up saying 'Are you sure you want to clear the cart?' with 'Yes' and 'No' buttons.

![hd - show conf pop-up clear cart](https://cloud.githubusercontent.com/assets/2522583/5716688/52d22ee4-9b19-11e4-8fa9-2299533b4729.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
Verified in 'https://hairdom.herokuapp.com/', issue is fixed. Closing the issue.
