### ISSUE TITLE
General - Remove link from the phone number in footer section.

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/hairdom#2]
1) Open the website 'https://hairdom-staging.herokuapp.com/'.
2) Scroll to the end of the page and click on the phone number link.

Note: The link should not be available, instead the phone number should only be a text, else any supported application like Skype is being invoked, and an error message (see screenshot) is shown if user denies access to the third party application.
![hd - remove link from phone number](https://cloud.githubusercontent.com/assets/2522583/5690727/18055eb8-98c5-11e4-8f57-767369a29fd5.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
Verified in 'https://hairdom.herokuapp.com/', issue is fixed. Closing the issue.
