### ISSUE TITLE
Address - 'Save My Address' text is shown in English rather than in French.

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/hairdom#29]
1) Open the website 'https://hairdom.herokuapp.com/'.
2) Sign Up using a vlid email address and go to 'Adresse' page.
3) Scroll down and look at the 'Save My Address' checkbox.

Note: The site shows the text in English language rather than in French.

![hd - save my address in english](https://cloud.githubusercontent.com/assets/2522583/5722707/8ad04a56-9b64-11e4-956e-77274dd68243.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
Verified in 'https://hairdom.herokuapp.com/' in French page, issue is fixed. Closing the issue.
