### ISSUE TITLE
Products: Link at the end of the products list should be in French

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/hairdom#32]
1) Open the website 'https://hairdom.herokuapp.com/'.
2) Go to Products page (https://hairdom.herokuapp.com/products) and scroll to the bottom.

Note: The words with the links are in English, please change them to French as follows:

a) First = Première
b) Last = Dernier
c) Previous = Précédent
d) Next = Suivant

Also leave more gap between the links.

![pro - pagination text to fr](https://cloud.githubusercontent.com/assets/2522583/5999335/efab3322-aaf6-11e4-88aa-20c195f69233.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
Verified in 'https://hairdom.herokuapp.com/', issue is fixed. Closing the issue.
