### ISSUE TITLE
General - Site shows 'SHOP' at the top and quickly changes it to 'BOUTIQUE'

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/hairdom#34]
When the site 'https://hairdom.herokuapp.com/' is opened in any browser, at the top of the page the site shows 'SHOP' and then replaces the text with 'BOUTIQUE'.

Videoshot: http://tinypic.com/r/2el4ccz/8

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
Verified in 'https://hairdom.herokuapp.com/', issue is fixed. Closing the issue.
