### ISSUE TITLE
Product - The font size of the Product name should be little bigger

### ISSUE THREAD

**Issue by kkannappan** [LordAlexWorks/hairdom#4]
1) Open the website 'https://hairdom-staging.herokuapp.com/'.
2) Go to Products page (https://hairdom-staging.herokuapp.com/products).
3) Look at the Font size of the product name and the price.

Note: Site shows the Product name in smaller font and the price in bigger font. The font size of the Product name and the categories on the left nav should be little bigger.

![hd - product name small font](https://cloud.githubusercontent.com/assets/2522583/5690747/8eb754c0-98c6-11e4-9c00-13072746fb2a.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
Verified in 'https://hairdom.herokuapp.com/', issue is fixed. Closing the issue.
