### ISSUE TITLE
Home don't display the product code

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/hairdom#8]
![hairdom_-_your_hair__our_products_-_hairdom](https://cloud.githubusercontent.com/assets/72155/5692293/8f9e55b0-98c5-11e4-8713-20c03b9cda47.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
Verified in 'https://hairdom.herokuapp.com/', issue is fixed. Closing the issue.
